SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_NewMatchType]
	@TypeID CHAR(1),
	@MatchType VARCHAR(15)
AS 
BEGIN 
	BEGIN TRY 
		INSERT INTO dbo.MatchType
		VALUES (@TypeID, @MatchType)
	END TRY
    BEGIN CATCH 
		THROW 
	END CATCH 
END
GO
