GRANT INSERT ON SCHEMA:: [dbo] TO [dbrole_Admin]
GO
GRANT DELETE ON SCHEMA:: [dbo] TO [dbrole_Admin]
GO
GRANT UPDATE ON SCHEMA:: [dbo] TO [dbrole_Admin]
GO
GRANT EXECUTE ON SCHEMA:: [dbo] TO [dbrole_Admin]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [dbrole_Coach]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [dbrole_Player]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [IFT530]
GO
GRANT INSERT ON SCHEMA:: [dbo] TO [IFT530]
GO
GRANT UPDATE ON SCHEMA:: [dbo] TO [IFT530]
GO
GRANT EXECUTE ON SCHEMA:: [dbo] TO [IFT530]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [player]
GO
